Vagrant.configure("2") do |config|
config.vm.define :firewall do |firewall|
firewall.vm.box = "bento/centos-7.7"
firewall.vm.network :private_network, ip: "192.168.50.10"
firewall.vm.network :public_network, bridge: 'eth2: Intel(R) Wireless-AC 9462', ip:"192.168.0.20"
firewall.vm.provision "shell", path: 'D:\Descarga\servicios\parcial_final\firewall.sh'
firewall.vm.hostname = "firewall"
end
config.vm.define :servidor do |servidor|
servidor.vm.box = "bento/centos-7.7"
servidor.vm.network :private_network, ip: "192.168.50.11"
servidor.vm.provision "shell", path: 'D:\Descarga\servicios\parcial_final\servidor.sh'
servidor.vm.hostname = "servidor"
end
end
