Vagrant.configure("2") do |config|
config.vm.define :maquina do |maquina|
maquina.vm.box = "bento/ubuntu-19.10"
maquina.vm.network :private_network, ip: "192.168.50.3"
maquina.vm.hostname = "maquina"
end
end
